language:
  - c
  - cpp
  - go
  - d
  - crystal
  - rust

addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-gfx-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev

matrix:
  include:
    - os: linux
      compiler: gcc

script:
  - make -C c11
  - make -C c++98
  - make -C c++11
  - pushd go
  - go get -d -v
  - go build
  - go test
  - popd
  - make -C d
  - make -C crystal
  - make -C rust

#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.freenode.net#blabla"
#    on_success: change
#    on_failure: always
#    template:
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
#    use_notice: true
#    skip_join: true
