language:
  - c
  - cpp
  - go
  - python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - python -V
  - cmake --version
  - make --version
  - make -C c++11
  - make -C c++98
  - make -C c11
  - pushd go
  - go build
  - go test
  - popd

#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.freenode.net#blabla"
#    on_success: change
#    on_failure: always
#    template:
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
#    use_notice: true
#    skip_join: true
