name: sdl2-examples

on:
  push:
    branches:
    - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
    - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests_list:
        - { folder: "c++11-cmake", type: "cmake" }
        - { folder: "c++14-cmake", type: "cmake" }
        - { folder: "c++17-cmake", type: "cmake" }
        - { folder: "c++20-cmake", type: "cmake" }
    steps:
      - uses: actions/checkout@v2
      - name: install_dependencies
        run: |
          sudo apt-get install -y libsdl2-dev ninja-build cmake
      - name: build
        run: |
              cd ${{ matrix.tests_list.folder }}
              cmake -S . -B build -G Ninja
              ninja -C build

